version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: zabbix-database
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - /volumes/zabbix/database:/var/lib/mysql
    networks:
      - zabbix-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --log_bin_trust_function_creators=1
    restart: always

  server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-database
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
      - "10051:10051"
    depends_on:
      - database
    networks:
      - zabbix-network
    restart: always

  web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-database
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8229:8080"
      - "8443:8443"
    depends_on:
      - server
    networks:
      - zabbix-network
    restart: always

  java-gateway:
    image: zabbix/zabbix-java-gateway:latest
    container_name: zabbix-java-gateway
    networks:
      - zabbix-network
    restart: always

networks:
  zabbix-network:
    external: true
